#
# Production Stack
#

#
# WEO Frontend Load Balancer
#
weo_lb:
  image: 'tutum/haproxy:latest'
  tags:
    - production
  links:
    - weo
  ports:
    - '80:80'
    - '443:443'
  roles:
    - global
  environment:
    BACKEND_PORT: 3000
    # SSL Certificate String is the concatenation of
    # the private key and the public certificate, with
    # newlines replaced with '\n'.
    #
    # It can be produced with this command:
    # cat private.pem public.pem | awk 1 ORS='\\n'
    SSL_CERT: -----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA4IzOBDie4g35JvLX9AE4NgB5TA14F+wI3859cc1+cz8uw9Mj\nH/Adwl7jSJASn0Sb0VYLprA6VY7uez41uAxf51EXRkCiMvXHHZUKe6Jy5eTFhTAr\nUL26/yzbJiklNCYa20BhrMXq+idRH7b3XSyO8LG7pzk1Nkc9Xhn7D7JORJLEVshz\nt60LQVwcKr0/hpL71Q+LywyrRlxHLVGZnDuMGfL8pO/hLQjaQsqPgfYyVj6S50+c\nwysiHBFRIue1hzHIeihxbmHyFBkPOx4K2W9AjuR7ReTMTc2n/+7XVf3atoPojL1W\n/qCrLOPsj4pNloWKIhURY8MlNJ4iZL4txfoYDQIDAQABAoIBADtyS2AmtTlXRayg\nAbfhUsZJHdOahT6gCEFn4yHrqxxLj8/b56Ke6OH6SOV+7s8nVLD4vKDmaqsX6d7K\nu2H8NK+Cckzw83/WPV6BhILyoMRn6jq2Y+E+OXEwqNvTbLv/koCU7MbWpryPCBUD\nVT1ffIAQLYO5y3KRLZfp/ONM6xeP3C4fvJXoCC+F5axEMySnxYBhqqVJFUHod+xP\nv2+4d9+BEErtcpDpEl6HC0egL6fyEK0djsU3O+7o6Vm+3YWV4gop61VmEEQdBTGj\nrBVShFuBJu1Hsq5op4DXxDpH4ld8QvdHmW/zeEo2eFysqcFpNykhdBF5QvZYDh2d\nldLqb0ECgYEA/fgoRA4/WFolVFqlREIrgKhY2/tJwtH/3qr1KqUsf6OAMxgmZG1o\nddplfUHDjHd4EIiBsDOrUctxGTX4BNxOS6Zek9IPCKcfL2iZHcO/HPVNcZcB9cIN\nZMjee3XmgFUcc+8BQaij/ve9lhQ78Kh1cKruuuBuZIP9F9bvIFpNeZkCgYEA4lhu\nCb8jieQGkqmsZX2reFblU7nebtQvK/j3is0JrxBM1x/tnXhOVdXx5XHP6vON/P8w\nMcASo5NV8A8L+Ll5sxDvHWRaJZCL12b4wd4F7frVPRzj9cQYeDFwMR1SsEssk4Ud\nbTGtHCTg5GD3zbdlWH5uABB1S79PYUn4MqAcIpUCgYBzBB+4Mnudl7WwLh0KfK0W\n5ybW+Ua+ZDxsqx+84HD2nSVB/n3knWfhd7besxnMU46cbjXNhpjfwjLGKBramKsc\nt4u9hjQoxwbogYZWZH/4rV8VQj4w/mDyc8XOQ+bP17u7BVKcWbNrlObXQPKkWqZV\nEBRtrZZRDzVfxoclL8BGgQKBgQDKeTJN87aVxe3/SlqWGznFF25jXDRWzeY4nqjJ\neCr+eEVUdxI2uATTEeQmTI4ibaaJN7nj9x51RvosGTmrUDdGcJKFp1xgmBIQKOPD\ngJmrTaNs3KgrFDSTaB4lQUbTvxtsBzrQkAx7zZ2Djh593l2BMO+zjQVwMf2PWPz2\nRHWGlQKBgAYKxS3d2vuyUi46E9UAUFOtlum3mI+on7OBX/TMpBXLMxks0L7wTjjV\nqHPHN9jGPw0Bhu7iqz2Cl7HP/6w40evs4pxz3FHjIFF/BeTouhYOALB6/AXoKo4f\nASyons5rY8+GUfzuy5+A5pZ+iUd55obgS9Nraqtz5cWz60q33yjr\n-----END RSA PRIVATE KEY-----\n-----BEGIN CERTIFICATE-----\nMIIHezCCBmOgAwIBAgIQCKPdRFocVE+ycs6/M19p8jANBgkqhkiG9w0BAQsFADB1\nMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\nd3cuZGlnaWNlcnQuY29tMTQwMgYDVQQDEytEaWdpQ2VydCBTSEEyIEV4dGVuZGVk\nIFZhbGlkYXRpb24gU2VydmVyIENBMB4XDTE1MDQwODAwMDAwMFoXDTE2MDQxMjEy\nMDAwMFowggECMR0wGwYDVQQPDBRQcml2YXRlIE9yZ2FuaXphdGlvbjETMBEGCysG\nAQQBgjc8AgEDEwJVUzEbMBkGCysGAQQBgjc8AgECEwpDYWxpZm9ybmlhMREwDwYD\nVQQFEwhDMzQ4NTc5MzEcMBoGA1UECRMTOTMxIE4uIEhpZ2hsYW5kIEF2ZTEOMAwG\nA1UEERMFOTAwMzgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRQw\nEgYDVQQHEwtMb3MgQW5nZWxlczEhMB8GA1UEChMYV0VPIEVkdWNhdGlvbmFsIFNv\nZnR3YXJlMRMwEQYDVQQDEwp3d3cud2VvLmlvMIIBIjANBgkqhkiG9w0BAQEFAAOC\nAQ8AMIIBCgKCAQEA4IzOBDie4g35JvLX9AE4NgB5TA14F+wI3859cc1+cz8uw9Mj\nH/Adwl7jSJASn0Sb0VYLprA6VY7uez41uAxf51EXRkCiMvXHHZUKe6Jy5eTFhTAr\nUL26/yzbJiklNCYa20BhrMXq+idRH7b3XSyO8LG7pzk1Nkc9Xhn7D7JORJLEVshz\nt60LQVwcKr0/hpL71Q+LywyrRlxHLVGZnDuMGfL8pO/hLQjaQsqPgfYyVj6S50+c\nwysiHBFRIue1hzHIeihxbmHyFBkPOx4K2W9AjuR7ReTMTc2n/+7XVf3atoPojL1W\n/qCrLOPsj4pNloWKIhURY8MlNJ4iZL4txfoYDQIDAQABo4IDdjCCA3IwHwYDVR0j\nBBgwFoAUPdNQpdagre7zSmAKZdMh1Pj41g8wHQYDVR0OBBYEFEyqcqJXJu8jqhZl\nLgwXoxzqd4GUMCkGA1UdEQQiMCCCCnd3dy53ZW8uaW+CCmFwaS53ZW8uaW+CBndl\nby5pbzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF\nBwMCMHUGA1UdHwRuMGwwNKAyoDCGLmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9z\naGEyLWV2LXNlcnZlci1nMS5jcmwwNKAyoDCGLmh0dHA6Ly9jcmw0LmRpZ2ljZXJ0\nLmNvbS9zaGEyLWV2LXNlcnZlci1nMS5jcmwwQgYDVR0gBDswOTA3BglghkgBhv1s\nAgEwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzCB\niAYIKwYBBQUHAQEEfDB6MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2Vy\ndC5jb20wUgYIKwYBBQUHMAKGRmh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9E\naWdpQ2VydFNIQTJFeHRlbmRlZFZhbGlkYXRpb25TZXJ2ZXJDQS5jcnQwDAYDVR0T\nAQH/BAIwADCCAYAGCisGAQQB1nkCBAIEggFwBIIBbAFqAHcApLkJkLQYWBSHuxOi\nzGdwCjw1mAT5G9+443fNDsgN3BAAAAFMmy/N0wAABAMASDBGAiEA3e4HlxSZt1JK\nGov9gIqFNN9ltb62CGWue4zpEeSnnggCIQCsj+9ClWEYLrQg9Mhaci2bQGUHWEzy\niP3janAtizzEeQB3AGj2mPgfZIK+OozuuSgdTPxxUV1nk9RE0QpnrLtPT/vEAAAB\nTJsvzZMAAAQDAEgwRgIhAPtSW3Li+ucFZaajS2UCer2GcES0MznSUoffRhyKRH72\nAiEA1+J5eIxm88TcNiWZ3ilAiRQebQGLYtpa1yPUw362VgIAdgBWFAaaL9fC7NP1\n4b1Esj7HRna5vJkRXMDvlJhV1onQ3QAAAUybL86RAAAEAwBHMEUCIDONYRj3A1Ja\nRCfXNTshnAY0QrJPbBD1CmacnWUelvZDAiEAzUZ12q6M08OF+UtBOk14ME8hk9Of\nIqzgsBJbFzKm1q8wDQYJKoZIhvcNAQELBQADggEBADXPVWN8KEhT5qTmGUcbvLvf\nOD51Og4dap0KpKx4sMAUKS03nt3N08dUrVVTDjhjivp4oF0D3rdOpvWRKn0nOONi\ndoDKK6slxa6LKQvmvT5seagj2dQaboFgbXSut1ydDYHRNNSgN4Y//IXACsffJG+w\nMMOTQI5sXxrgNQIB3Vx/c8pG2e8UHABgjb5PXGRei/ixMwqIEgUmQz2evGd1szsc\nmuc37knF6SIeswn+I6QXc+IvnPxynC97u1DatFx3v7BOTVpI1KG/23v4DXYQSr1l\n1kn5Sy8XtB+VzeyziKs8OT6bFcfkqW9fYmtFF2ntJXewMy+O7ur9wx10kQBU4bs=\n-----END CERTIFICATE-----\n

#
# WEO Frontend Server
#
weo:
  image: 'tutum.co/ashaffer/eos-core:production'
  target_num_containers: 2
  tags:
    - production
  expose:
    - '3000'
  environment:
    PORT: 3000
    API_SERVER: //api.weo.io
    API_STATIC: //weo-api.global.ssl.fastly.net
    STATIC_FILES: //weo.global.ssl.fastly.net
    AVATAR_SERVER: //cdn-eos-io.global.ssl.fastly.net
    CLEVER_CLIENT_ID: 504ffa19024513570be4
    CRAWLABLE: true
    GOOGLE_CLIENT_ID: 696300823052-gluo2j11ec7jfocj7opqt8qpmosbducq.apps.googleusercontent.com
    NODE_ENV: production
    SEGMENT_IO_KEY: 0mhgcgv6ao
    IMAGE_SERVER: //images.global.ssl.fastly.net


#
# API Backend Load Balancer
#
api_lb:
  image: 'tutum/haproxy:latest'
  tags:
    - production
  links:
    - api
  ports:
    - '80:80'
    - '443:443'
  roles:
    - global
  environment:
    BACKEND_PORT: 3000
    SESSION_COOKIE: io  # use socket.io's io session cookie for
                        # session persistence

    # SSL Certificate String is the concatenation of
    # the private key and the public certificate, with
    # newlines replaced with '\n'.
    #
    # It can be produced with this command:
    # cat private.pem public.pem | awk 1 ORS='\\n'
    SSL_CERT: -----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEA4IzOBDie4g35JvLX9AE4NgB5TA14F+wI3859cc1+cz8uw9Mj\nH/Adwl7jSJASn0Sb0VYLprA6VY7uez41uAxf51EXRkCiMvXHHZUKe6Jy5eTFhTAr\nUL26/yzbJiklNCYa20BhrMXq+idRH7b3XSyO8LG7pzk1Nkc9Xhn7D7JORJLEVshz\nt60LQVwcKr0/hpL71Q+LywyrRlxHLVGZnDuMGfL8pO/hLQjaQsqPgfYyVj6S50+c\nwysiHBFRIue1hzHIeihxbmHyFBkPOx4K2W9AjuR7ReTMTc2n/+7XVf3atoPojL1W\n/qCrLOPsj4pNloWKIhURY8MlNJ4iZL4txfoYDQIDAQABAoIBADtyS2AmtTlXRayg\nAbfhUsZJHdOahT6gCEFn4yHrqxxLj8/b56Ke6OH6SOV+7s8nVLD4vKDmaqsX6d7K\nu2H8NK+Cckzw83/WPV6BhILyoMRn6jq2Y+E+OXEwqNvTbLv/koCU7MbWpryPCBUD\nVT1ffIAQLYO5y3KRLZfp/ONM6xeP3C4fvJXoCC+F5axEMySnxYBhqqVJFUHod+xP\nv2+4d9+BEErtcpDpEl6HC0egL6fyEK0djsU3O+7o6Vm+3YWV4gop61VmEEQdBTGj\nrBVShFuBJu1Hsq5op4DXxDpH4ld8QvdHmW/zeEo2eFysqcFpNykhdBF5QvZYDh2d\nldLqb0ECgYEA/fgoRA4/WFolVFqlREIrgKhY2/tJwtH/3qr1KqUsf6OAMxgmZG1o\nddplfUHDjHd4EIiBsDOrUctxGTX4BNxOS6Zek9IPCKcfL2iZHcO/HPVNcZcB9cIN\nZMjee3XmgFUcc+8BQaij/ve9lhQ78Kh1cKruuuBuZIP9F9bvIFpNeZkCgYEA4lhu\nCb8jieQGkqmsZX2reFblU7nebtQvK/j3is0JrxBM1x/tnXhOVdXx5XHP6vON/P8w\nMcASo5NV8A8L+Ll5sxDvHWRaJZCL12b4wd4F7frVPRzj9cQYeDFwMR1SsEssk4Ud\nbTGtHCTg5GD3zbdlWH5uABB1S79PYUn4MqAcIpUCgYBzBB+4Mnudl7WwLh0KfK0W\n5ybW+Ua+ZDxsqx+84HD2nSVB/n3knWfhd7besxnMU46cbjXNhpjfwjLGKBramKsc\nt4u9hjQoxwbogYZWZH/4rV8VQj4w/mDyc8XOQ+bP17u7BVKcWbNrlObXQPKkWqZV\nEBRtrZZRDzVfxoclL8BGgQKBgQDKeTJN87aVxe3/SlqWGznFF25jXDRWzeY4nqjJ\neCr+eEVUdxI2uATTEeQmTI4ibaaJN7nj9x51RvosGTmrUDdGcJKFp1xgmBIQKOPD\ngJmrTaNs3KgrFDSTaB4lQUbTvxtsBzrQkAx7zZ2Djh593l2BMO+zjQVwMf2PWPz2\nRHWGlQKBgAYKxS3d2vuyUi46E9UAUFOtlum3mI+on7OBX/TMpBXLMxks0L7wTjjV\nqHPHN9jGPw0Bhu7iqz2Cl7HP/6w40evs4pxz3FHjIFF/BeTouhYOALB6/AXoKo4f\nASyons5rY8+GUfzuy5+A5pZ+iUd55obgS9Nraqtz5cWz60q33yjr\n-----END RSA PRIVATE KEY-----\n-----BEGIN CERTIFICATE-----\nMIIHezCCBmOgAwIBAgIQCKPdRFocVE+ycs6/M19p8jANBgkqhkiG9w0BAQsFADB1\nMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\nd3cuZGlnaWNlcnQuY29tMTQwMgYDVQQDEytEaWdpQ2VydCBTSEEyIEV4dGVuZGVk\nIFZhbGlkYXRpb24gU2VydmVyIENBMB4XDTE1MDQwODAwMDAwMFoXDTE2MDQxMjEy\nMDAwMFowggECMR0wGwYDVQQPDBRQcml2YXRlIE9yZ2FuaXphdGlvbjETMBEGCysG\nAQQBgjc8AgEDEwJVUzEbMBkGCysGAQQBgjc8AgECEwpDYWxpZm9ybmlhMREwDwYD\nVQQFEwhDMzQ4NTc5MzEcMBoGA1UECRMTOTMxIE4uIEhpZ2hsYW5kIEF2ZTEOMAwG\nA1UEERMFOTAwMzgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRQw\nEgYDVQQHEwtMb3MgQW5nZWxlczEhMB8GA1UEChMYV0VPIEVkdWNhdGlvbmFsIFNv\nZnR3YXJlMRMwEQYDVQQDEwp3d3cud2VvLmlvMIIBIjANBgkqhkiG9w0BAQEFAAOC\nAQ8AMIIBCgKCAQEA4IzOBDie4g35JvLX9AE4NgB5TA14F+wI3859cc1+cz8uw9Mj\nH/Adwl7jSJASn0Sb0VYLprA6VY7uez41uAxf51EXRkCiMvXHHZUKe6Jy5eTFhTAr\nUL26/yzbJiklNCYa20BhrMXq+idRH7b3XSyO8LG7pzk1Nkc9Xhn7D7JORJLEVshz\nt60LQVwcKr0/hpL71Q+LywyrRlxHLVGZnDuMGfL8pO/hLQjaQsqPgfYyVj6S50+c\nwysiHBFRIue1hzHIeihxbmHyFBkPOx4K2W9AjuR7ReTMTc2n/+7XVf3atoPojL1W\n/qCrLOPsj4pNloWKIhURY8MlNJ4iZL4txfoYDQIDAQABo4IDdjCCA3IwHwYDVR0j\nBBgwFoAUPdNQpdagre7zSmAKZdMh1Pj41g8wHQYDVR0OBBYEFEyqcqJXJu8jqhZl\nLgwXoxzqd4GUMCkGA1UdEQQiMCCCCnd3dy53ZW8uaW+CCmFwaS53ZW8uaW+CBndl\nby5pbzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF\nBwMCMHUGA1UdHwRuMGwwNKAyoDCGLmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9z\naGEyLWV2LXNlcnZlci1nMS5jcmwwNKAyoDCGLmh0dHA6Ly9jcmw0LmRpZ2ljZXJ0\nLmNvbS9zaGEyLWV2LXNlcnZlci1nMS5jcmwwQgYDVR0gBDswOTA3BglghkgBhv1s\nAgEwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzCB\niAYIKwYBBQUHAQEEfDB6MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2Vy\ndC5jb20wUgYIKwYBBQUHMAKGRmh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9E\naWdpQ2VydFNIQTJFeHRlbmRlZFZhbGlkYXRpb25TZXJ2ZXJDQS5jcnQwDAYDVR0T\nAQH/BAIwADCCAYAGCisGAQQB1nkCBAIEggFwBIIBbAFqAHcApLkJkLQYWBSHuxOi\nzGdwCjw1mAT5G9+443fNDsgN3BAAAAFMmy/N0wAABAMASDBGAiEA3e4HlxSZt1JK\nGov9gIqFNN9ltb62CGWue4zpEeSnnggCIQCsj+9ClWEYLrQg9Mhaci2bQGUHWEzy\niP3janAtizzEeQB3AGj2mPgfZIK+OozuuSgdTPxxUV1nk9RE0QpnrLtPT/vEAAAB\nTJsvzZMAAAQDAEgwRgIhAPtSW3Li+ucFZaajS2UCer2GcES0MznSUoffRhyKRH72\nAiEA1+J5eIxm88TcNiWZ3ilAiRQebQGLYtpa1yPUw362VgIAdgBWFAaaL9fC7NP1\n4b1Esj7HRna5vJkRXMDvlJhV1onQ3QAAAUybL86RAAAEAwBHMEUCIDONYRj3A1Ja\nRCfXNTshnAY0QrJPbBD1CmacnWUelvZDAiEAzUZ12q6M08OF+UtBOk14ME8hk9Of\nIqzgsBJbFzKm1q8wDQYJKoZIhvcNAQELBQADggEBADXPVWN8KEhT5qTmGUcbvLvf\nOD51Og4dap0KpKx4sMAUKS03nt3N08dUrVVTDjhjivp4oF0D3rdOpvWRKn0nOONi\ndoDKK6slxa6LKQvmvT5seagj2dQaboFgbXSut1ydDYHRNNSgN4Y//IXACsffJG+w\nMMOTQI5sXxrgNQIB3Vx/c8pG2e8UHABgjb5PXGRei/ixMwqIEgUmQz2evGd1szsc\nmuc37knF6SIeswn+I6QXc+IvnPxynC97u1DatFx3v7BOTVpI1KG/23v4DXYQSr1l\n1kn5Sy8XtB+VzeyziKs8OT6bFcfkqW9fYmtFF2ntJXewMy+O7ur9wx10kQBU4bs=\n-----END CERTIFICATE-----\n

#
# API Backend Server
#
api:
  image: 'tutum.co/ashaffer/api:production'
  tags:
    - production
  autoredeploy: true
  target_num_containers: 3
  links:
    - redis # We don't actually use the link or the env vars to connnect to
            # redis, but we need to put the link here to ensure redis boots up
            # before the API
  expose:
    - '3000'
  environment:
    PORT: 3000
    CLEVER_CLIENT_ID: 504ffa19024513570be4
    CLEVER_CLIENT_SECRET: 87b3e092190e5787a10c9e0e18886221b483a553
    DEBUG: weo:*
    EMAIL_FRONTEND: http://weo.io
    EMAIL_PASS: elliotrileytio
    EMAIL_USER: info@weo.io
    GOOGLE_CLIENT_ID: 696300823052-gluo2j11ec7jfocj7opqt8qpmosbducq.apps.googleusercontent.com
    GOOGLE_SECRET: POE6EaRNeXWLP8DPafQOBR-Y
    MONGO_URL: mongodb://db:X4ubrTLYLcDm8HS@c273.lighthouse.0.mongolayer.com:10273,c273.lighthouse.1.mongolayer.com:10273/eos?replicaSet=set-54e81ced9b093226ee0008ef
    NODE_ENV: production
    PAPERTRAIL_HOST: logs2.papertrailapp.com
    PAPERTRAIL_PORT: 15920
    S3_API_KEY: AKIAIIA5OZD3IKVSUXDA
    S3_UPLOAD_BUCKET: weo-uploads
    S3_UPLOAD_REGION: us-west-2
    S3_UPLOAD_SECRET: 5bvPGCODzU/rzfyjq6F0VQN7hkO4AWzqONRkclig
    REDIS_URL: redis://user:password@redis:6379
    SCRAPER_URL: http://scraper.weo.io/1/oembed/
    UPLOAD_SIZE_LIMIT: 5mb
    FASTLY_AVATAR_SERVICE_ID: 66wIYwgwWKRCkZVOIXILTd
    FASTLY_API_KEY: 5fcca7ec8ce5850f169a5589f0cf3a62

#
# Redis
#
redis:
  tags:
    - production
  image: 'tutum/redis:latest'
  expose:
    - '6379'
  environment:
    REDIS_PASS: password