#
#     Staging Stack
#

#
# WEO Frontend Load Balancer
#
weo_lb:
  image: 'tutum/haproxy:latest'
  links:
    - weo
  ports:
    - '80:80'
  roles:
    - global
  environment:
    BACKEND_PORT: 3000

#
# WEO Frontend Server
#
weo:
  image: 'tutum.co/ashaffer/eos-core:staging'
  autoredeploy: true
  expose:
    - '3000'
  environment:
    PORT: 3000
    API_SERVER: //staging-api.weo.io
    API_STATIC: //staging-api-cdn.weo.io
    AVATAR_SERVER: //cdn.eos.io.s3-website-us-west-1.amazonaws.com
    CLEVER_CLIENT_ID: 9e85d73ee95c90414fbd
    CRAWLABLE: false
    DEBUG: weo:*
    GOOGLE_CLIENT_ID: 696300823052-39m3901cceuiehfiac4s9l9su5tlps2r.apps.googleusercontent.com
    INTERCOM_APP_ID: so9uchl4
    NODE_ENV: staging
    PAPERTRAIL_HOST: logs2.papertrailapp.com
    PAPERTRAIL_PORT: 15920
    SEGMENT_IO_KEY: e6e7s7djli
    STATIC_FILES: //staging.weo.io
    UPLOAD_SERVER: //dev.eos.io.s3.amazonaws.com

#
# API Backend Load Balancer
#
api_lb:
  image: 'tutum/haproxy:latest'
  links:
    - api
  ports:
    - '80:80'
  roles:
    - global
  environment:
    BACKEND_PORT: 3000
    SESSION_COOKIE: io  # use socket.io's io session cookie for
                        # session persistence

#
# API Backend Server
#
api:
  image: 'tutum.co/ashaffer/api:staging'
  autoredeploy: true
  target_num_containers: 3
  links:
    - redis # We don't actually use the link or the env vars to connnect to
            # redis, but we need to put the link here to ensure redis boots up
            # before the API
  expose:
    - '3000'
  environment:
    PORT: 3000
    AVATAR_SERVER: //cdn.eos.io.s3-website-us-west-1.amazonaws.com
    CLEVER_CLIENT_ID: 9e85d73ee95c90414fbd
    CLEVER_CLIENT_SECRET: de3a5c71719741581ec2b77a05e07c643369560f
    DEBUG: weo:*
    EMAIL_FRONTEND: http://staging.weo.io
    EMAIL_PASS: themangthemang
    EMAIL_USER: testmail@weo.io
    GOOGLE_CLIENT_ID: 696300823052-39m3901cceuiehfiac4s9l9su5tlps2r.apps.googleusercontent.com
    GOOGLE_SECRET: Ou2xuWLoVp_JP23p0rNMnaC9
    HASH_ID_KEY: themang
    MONGO_URL: mongodb://eos:UGjJdj4fHjX5Qkq@c253.lighthouse.0.mongolayer.com:10253,c253.lighthouse.1.mongolayer.com:10253/default?replicaSet=set-54daa4019bb891b661000eea
    NODE_ENV: staging
    PAPERTRAIL_HOST: logs2.papertrailapp.com
    PAPERTRAIL_PORT: 15920
    REDIS_URL: redis://user:password@redis:6379/
    S3_API_KEY: AKIAIIA5OZD3IKVSUXDA
    S3_AVATAR_BUCKET: cdn.eos.io
    S3_AVATAR_REGION: us-west-1
    S3_AVATAR_SECRET: 5bvPGCODzU/rzfyjq6F0VQN7hkO4AWzqONRkclig
    S3_UPLOAD_BUCKET: dev.eos.io
    S3_UPLOAD_SECRET: 5bvPGCODzU/rzfyjq6F0VQN7hkO4AWzqONRkclig
    SCRAPER_URL: http://scraper/1/oembed/
    UPLOAD_SIZE_LIMIT: 5mb

#
# Redis
#
redis:
  image: 'tutum/redis:latest'
  expose:
    - '6379'
  environment:
    REDIS_PASS: password

#
# Link Scraper
#
scraper:
  image: 'tutum.co/ashaffer/scraper-proxy:staging'
  autoredeploy: true
  environment:
    DEBUG: scraper:*
    DOCTHUMB_URL: http://docthumb_lb/
    EMBEDLY_API_KEY: 578f2e0b9cb04763888f0a6c9b907b55
    GOOGLE_DRIVE_API_KEY: AIzaSyDCntpE09OxvK4vTsCTMlUKI-wlMi3H3SI
    PAPERTRAIL_HOST: logs2.papertrailapp.com
    PAPERTRAIL_PORT: 15920
    S3_API_KEY: AKIAJGRZMUAG422PORVQ
    S3_BUCKET: dev.eos.io
    S3_REGION: us-west-1
    S3_SECRET: VmldgplYd6qfga0HpE1KqsMiGBJDiA88OtyYTfbc

#
# Document Thumbnailer Load Balancer
#
docthumb_lb:
  image: 'tutum/haproxy:latest'
  environment:
    BACKEND_PORT: 3000
  links:
    - docthumb
  expose:
    - '80'
  roles:
    - global

#
# Document Thumbnailer
#
docthumb:
  image: 'tutum.co/ashaffer/docthumb:staging'
  autoredeploy: true
  environment:
    PORT: 3000
  expose:
    - '3000'
  target_num_containers: 3