#
#     Staging Stack
#

#
# WEO Frontend Load Balancer
#
weo_lb:
  image: 'tutum/haproxy:latest'
  tags:
    - staging
  links:
    - weo
  ports:
    - '80:80'
  roles:
    - global
  environment:
    BACKEND_PORT: 3000

#
# WEO Frontend Server
#
weo:
  image: 'tutum.co/ashaffer/eos-core:staging'
  tags:
    - staging
  autoredeploy: true
  expose:
    - '3000'
  environment:
    PORT: 3000
    API_SERVER: //staging-api.weo.io
    API_STATIC: //staging-api-cdn.weo.io
    AVATAR_SERVER: //staging-avatars.global.ssl.fastly.net
    CLEVER_CLIENT_ID: 9e85d73ee95c90414fbd
    FACEBOOK_APP_ID: 1696938930540934
    CRAWLABLE: false
    DEBUG: weo:*
    GOOGLE_CLIENT_ID: 696300823052-39m3901cceuiehfiac4s9l9su5tlps2r.apps.googleusercontent.com
    INTERCOM_APP_ID: so9uchl4
    NODE_ENV: staging
    PAPERTRAIL_HOST: logs2.papertrailapp.com
    PAPERTRAIL_PORT: 15920
    SEGMENT_IO_KEY: e6e7s7djli
    STATIC_FILES: //staging.weo.io
    IMAGE_SERVER: //images.weo.io
    WEO_SOURCEMAPS: true
    WEO_ENGAGE: "Get early access"

#
# API Backend Load Balancer
#
api_lb:
  image: 'tutum/haproxy:latest'
  tags:
    - staging
  links:
    - api
  ports:
    - '80:80'
  roles:
    - global
  environment:
    BACKEND_PORT: 3000
    SESSION_COOKIE: io  # use socket.io's io session cookie for
                        # session persistence

#
# API Backend Server
#
api:
  image: 'tutum.co/ashaffer/api:staging'
  tags:
    - staging
  autoredeploy: true
  target_num_containers: 3
  links:
    - redis # We don't actually use the link or the env vars to connnect to
            # redis, but we need to put the link here to ensure redis boots up
            # before the API
  expose:
    - '3000'
  environment:
    PORT: 3000
    CLEVER_CLIENT_ID: 9e85d73ee95c90414fbd
    CLEVER_CLIENT_SECRET: de3a5c71719741581ec2b77a05e07c643369560f
    DEBUG: weo:*
    EMAIL_FRONTEND: http://staging.weo.io
    EMAIL_PASS: themangthemang
    EMAIL_USER: testmail@weo.io
    MANDRILL_API_KEY: GAs1A7BXpHBZM5Rl2FLcig
    MAILCHIMP_API_KEY: 8a86dfde003377d5b2e32668c99369ce
    MAILCHIMP_DATACENTER: us11
    MAILCHIMP_INVITE_LIST_ID: 4c10c5f1a7
    GOOGLE_CLIENT_ID: 696300823052-39m3901cceuiehfiac4s9l9su5tlps2r.apps.googleusercontent.com
    GOOGLE_SECRET: Ou2xuWLoVp_JP23p0rNMnaC9
    MONGO_URL: mongodb://eos:UGjJdj4fHjX5Qkq@c253.lighthouse.0.mongolayer.com:10253,c253.lighthouse.1.mongolayer.com:10253/default?replicaSet=set-54daa4019bb891b661000eea
    NODE_ENV: staging
    PAPERTRAIL_HOST: logs2.papertrailapp.com
    PAPERTRAIL_PORT: 15920
    REDIS_URL: redis://user:password@redis:6379/
    S3_API_KEY: AKIAIIA5OZD3IKVSUXDA
    S3_UPLOAD_REGION: us-west-2
    S3_UPLOAD_BUCKET: weo-uploads-dev
    S3_UPLOAD_SECRET: 5bvPGCODzU/rzfyjq6F0VQN7hkO4AWzqONRkclig
    SCRAPER_URL: http://scraper.weo.io/1/oembed/
    UPLOAD_SIZE_LIMIT: 5mb
    FASTLY_API_KEY: 5fcca7ec8ce5850f169a5589f0cf3a62
    AVATAR_SERVER: //staging-avatars.global.ssl.fastly.net
    WEO_API_FEATURED: 5595a59342d1080b00920bfe,55ca9a978cb0b1100052be67,55b02d80c8a4620e00ef7fe9,54aaff61bf530f0200f351c7
    FACEBOOK_APP_ID: 1696938930540934
    FACEBOOK_SECRET: 35bb8416b0448f1df66c2e1e6a430350
    TEMPLATE_BOARD_ID: 560c603510322a8faf06f82d


#
# Redis
#
redis:
  image: 'tutum/redis:latest'
  tags:
    - staging
  expose:
    - '6379'
  environment:
    REDIS_PASS: password
